### ISSUE TITLE
Null-safety of stubbed return values

### ISSUE THREAD

**Issue by andrewazores** [jessyec-s/openjdk8-jfr-compat#3]
https://github.com/jessyec-s/openjdk8-jfr-compat/blob/3bd939487127f7cc4a3f747bce58a60b894096a6/src/main/java/jdk/jfr/consumer/RecordedClass.java#L43

This stubbed method is defined to return `null`, however, the API docs state that the returned value will not be null: https://docs.oracle.com/en/java/javase/11/docs/api/jdk.jfr/jdk/jfr/consumer/RecordedClass.html#getName()

I haven't audited any further so there may be more similar instances of API violations.

I'm not sure exactly what the right thing to return here instead might be (empty string?), but since the API is documented to have a non-null return then it's reasonable to think that some code that may end up using this compatibility shim will be written in a way that is not null-safe, and in such a scenario this compatibility shim will lead to NPE for consumers.

**Comment by andrewazores** [comment]
https://docs.oracle.com/en/java/javase/11/docs/api/jdk.jfr/jdk/jfr/consumer/RecordedEvent.html

https://github.com/jessyec-s/openjdk8-jfr-compat/blob/master/src/main/java/jdk/jfr/consumer/RecordedEvent.java

`getStartTime`/`getEndTime` are also nullability API violations, so from a quick glance I think all of the stubs should be carefully examined for this class of issue.

**Comment by jessyec-s** [comment]
Fixed with b30702a . Where NPEs could occur I have changed return values from null to empty strings or to their corresponding correct return types.  Also, I have changed other methods' return values to null or other specific values, such as -1,  in cases where they are said to exist in the API docs for a specific method.
