### ISSUE TITLE
Statically allocate dummy values where applicable

### ISSUE THREAD

**Issue by andrewazores** [jessyec-s/openjdk8-jfr-compat#4]
For example: https://github.com/jessyec-s/openjdk8-jfr-compat/blob/3bd939487127f7cc4a3f747bce58a60b894096a6/src/main/java/jdk/jfr/consumer/RecordedEvent.java#L65

This method call will allocate a new empty list every time it is invoked, but it's always an empty writeable list. The API doc is not explicit about whether the returned list is intended to be read-only, but upon reading the real implementation it does appear that the returned value is wrapped in a `Collections.unmodifiableList`. For this reason I believe it would be reasonable to implement the stub as `return Collections.emptyList()`.

Other compatibility methods should be investigated as well. If a Collection type is returned then an unmodifiable empty variant should be preferred to a writeable allocation whenever possible. If a different type is returned such as a `Duration`, then perhaps `Duration.ZERO` would be an appropriate dummy value in many/most situations.

**Comment by jessyec-s** [comment]
Fixed with 43d6d03 .  Where applicable, I have changed Collection types to be immutable and empty on return.
