### ISSUE TITLE
README is potentially misleading

### ISSUE THREAD

**Issue by andrewazores** [jessyec-s/openjdk8-jfr-compat#6]
"JFR support is provided through the resulting jar" sounds misleading - a consumer of this compatibility shim could reasonably read this and expect to gain actual JFR functionality (ie the ability to create, retrieve, etc. Flight Recordings) by adding this JAR to their classpath. The README should be rephrased to make it more clear that this compatibility is to allow applications with dependencies on the `jdk.jfr` package to *compile*, not to actually add Flight Recorder support as a feature.

**Comment by jessyec-s** [comment]
Fixed with cfa0da8
